export const URLs = {
    meApi: '/me',
    ApiLogin: '/signin',
    ApiSignUp: '/signup',
    ApiForgotPassword: '/reset-password',
    ApiUpdatePasswprd: '/update-password',
    ApiGetModel: 'model',
    ApiGetCategory: '/model/category',
    GETPAYMENTMETHOD: 'stripe/payment-method',
    DELETEPAYMENTMETHOD: '/stripe/payment-method',
    DEFAULTPAYMENTMETHOD: '/stripe/payment-method',
    ADDPAYMENTMETHOD: '/stripe/payment-method/',
    ChatRoom: '/chat/room',
    GetConversation: '/chat/conversation',
    chat: '/chat/stream',
    PAYMNET_PLANS: '/stripe/products',
    SUBSCRIPTION: '/stripe/subscription',
    PLAN_DETAILS: '/planDetails',
    ThresholdAdded: '/alerts',
    LIMITS_STATUS: 'credit/status',
    CANCEL_MY_PLAN: '/stripe/subscription',
};
